resources:
  - name: source
    type: git
    source:
      uri: https://github.com/candidpartners/concourse-cicd-demo.git

jobs:
  - name: serviceOne
    serial: true
    plan:
      - get: source
        trigger: true

      - task: settings
        params:
          ENV: ((environment))
          PIPELINE: 1
        config:
          platform: linux
          inputs:
            - name: source
          outputs:
            - name: settings
          image_resource:
            type: docker-image
            source:
              repository: 005901988046.dkr.ecr.us-east-2.amazonaws.com/concourse-worker
              tag: latest
              aws_access_key_id: ((aws_access_key_id))
              aws_secret_access_key: ((aws_secret_access_key))
          run:
            dir: source
            path: make
            args:
              - settings

      - task: infrastructure-deploy
        params:
          ENV: ((environment))
          PIPELINE: 1
          AWS_ACCESS_KEY_ID: ((aws_access_key_id))
          AWS_SECRET_ACCESS_KEY: ((aws_secret_access_key))
        config:
          platform: linux
          inputs:
            - name: source
            - name: settings
          outputs:
            - name: settings
          image_resource:
            type: docker-image
            source:
              repository: 005901988046.dkr.ecr.us-east-2.amazonaws.com/concourse-worker
              tag: latest
              aws_access_key_id: ((aws_access_key_id))
              aws_secret_access_key: ((aws_secret_access_key))
          run:
            dir: source/serviceOne/infrastructure
            path: make

      # Install dependencies, run unit tests, create webpack bundle, build
      - task: lambda-build
        params:
          ENV: ((environment))
          PIPELINE: 1
        config:
          platform: linux
          inputs:
            - name: source
            - name: settings
          outputs:
            - name: source
            - name: build
          image_resource:
            type: docker-image
            source:
              repository: 005901988046.dkr.ecr.us-east-2.amazonaws.com/concourse-worker
              tag: latest
              aws_access_key_id: ((aws_access_key_id))
              aws_secret_access_key: ((aws_secret_access_key))
          run:
            dir: source/serviceOne/lambda
            path: make
            args:
              - build

      - task: lambda-test
        params:
          ENV: ((environment))
          PIPELINE: 1
        config:
          platform: linux
          inputs:
            - name: source
            - name: settings
          image_resource:
            type: docker-image
            source:
              repository: 005901988046.dkr.ecr.us-east-2.amazonaws.com/concourse-worker
              tag: latest
              aws_access_key_id: ((aws_access_key_id))
              aws_secret_access_key: ((aws_secret_access_key))
          run:
            dir: source/serviceOne/lambda
            path: make
            args:
              - test

      - task: lambda-deploy
        params:
          ENV: ((environment))
          PIPELINE: 1
          AWS_ACCESS_KEY_ID: ((aws_access_key_id))
          AWS_SECRET_ACCESS_KEY: ((aws_secret_access_key))
        config:
          platform: linux
          inputs:
            - name: settings
            - name: build
            - name: source
          image_resource:
            type: docker-image
            source:
              repository: 005901988046.dkr.ecr.us-east-2.amazonaws.com/concourse-worker
              tag: latest
              aws_access_key_id: ((aws_access_key_id))
              aws_secret_access_key: ((aws_secret_access_key))
          run:
            dir: source/serviceOne/lambda
            path: make
            args:
              - deploy

      - task: functional-tests
        params:
          ENV: ((environment))
          PIPELINE: 1
          AWS_ACCESS_KEY_ID: ((aws_access_key_id))
          AWS_SECRET_ACCESS_KEY: ((aws_secret_access_key))
        config:
          platform: linux
          inputs:
            - name: source
            - name: settings
          image_resource:
            type: docker-image
            source:
              repository: 005901988046.dkr.ecr.us-east-2.amazonaws.com/concourse-worker
              tag: latest
              aws_access_key_id: ((aws_access_key_id))
              aws_secret_access_key: ((aws_secret_access_key))
          run:
            dir: source/serviceOne/functional_tests
            path: make
            args:
              - test

  - name: serviceTwo
    serial: true
    plan:
      - get: source
        trigger: true

      - task: settings
        params:
          ENV: ((environment))
          PIPELINE: 1
        config:
          platform: linux
          inputs:
            - name: source
          outputs:
            - name: settings
          image_resource:
            type: docker-image
            source:
              repository: 005901988046.dkr.ecr.us-east-2.amazonaws.com/concourse-worker
              tag: latest
              aws_access_key_id: ((aws_access_key_id))
              aws_secret_access_key: ((aws_secret_access_key))
          run:
            dir: source
            path: make
            args:
              - settings

      - task: infrastructure-deploy
        params:
          ENV: ((environment))
          PIPELINE: 1
          AWS_ACCESS_KEY_ID: ((aws_access_key_id))
          AWS_SECRET_ACCESS_KEY: ((aws_secret_access_key))
        config:
          platform: linux
          inputs:
            - name: source
            - name: settings
          outputs:
            - name: settings
          image_resource:
            type: docker-image
            source:
              repository: 005901988046.dkr.ecr.us-east-2.amazonaws.com/concourse-worker
              tag: latest
              aws_access_key_id: ((aws_access_key_id))
              aws_secret_access_key: ((aws_secret_access_key))
          run:
            dir: source/serviceTwo/infrastructure
            path: make

      # Install dependencies, run unit tests, create webpack bundle, build
      - task: lambda-build
        params:
          ENV: ((environment))
          PIPELINE: 1
        config:
          platform: linux
          inputs:
            - name: source
            - name: settings
          outputs:
            - name: source
            - name: build
          image_resource:
            type: docker-image
            source:
              repository: 005901988046.dkr.ecr.us-east-2.amazonaws.com/concourse-worker
              tag: latest
              aws_access_key_id: ((aws_access_key_id))
              aws_secret_access_key: ((aws_secret_access_key))
          run:
            dir: source/serviceTwo/lambda
            path: make
            args:
              - build

      - task: lambda-test
        params:
          ENV: ((environment))
          PIPELINE: 1
        config:
          platform: linux
          inputs:
            - name: source
            - name: settings
          image_resource:
            type: docker-image
            source:
              repository: 005901988046.dkr.ecr.us-east-2.amazonaws.com/concourse-worker
              tag: latest
              aws_access_key_id: ((aws_access_key_id))
              aws_secret_access_key: ((aws_secret_access_key))
          run:
            dir: source/serviceTwo/lambda
            path: make
            args:
              - test

      - task: lambda-deploy
        params:
          ENV: ((environment))
          PIPELINE: 1
          AWS_ACCESS_KEY_ID: ((aws_access_key_id))
          AWS_SECRET_ACCESS_KEY: ((aws_secret_access_key))
        config:
          platform: linux
          inputs:
            - name: settings
            - name: build
            - name: source
          image_resource:
            type: docker-image
            source:
              repository: 005901988046.dkr.ecr.us-east-2.amazonaws.com/concourse-worker
              tag: latest
              aws_access_key_id: ((aws_access_key_id))
              aws_secret_access_key: ((aws_secret_access_key))
          run:
            dir: source/serviceTwo/lambda
            path: make
            args:
              - deploy

      - task: functional-tests
        params:
          ENV: ((environment))
          PIPELINE: 1
          AWS_ACCESS_KEY_ID: ((aws_access_key_id))
          AWS_SECRET_ACCESS_KEY: ((aws_secret_access_key))
        config:
          platform: linux
          inputs:
            - name: source
            - name: settings
          image_resource:
            type: docker-image
            source:
              repository: 005901988046.dkr.ecr.us-east-2.amazonaws.com/concourse-worker
              tag: latest
              aws_access_key_id: ((aws_access_key_id))
              aws_secret_access_key: ((aws_secret_access_key))
          run:
            dir: source/serviceTwo/functional_tests
            path: make
            args:
              - test
