resources:
  - name: source
    type: git
    source:
      uri: https://github.com/candidpartners/concourse-cicd-demo.git

jobs:
  - name: deploy
    serial: true
    plan:
      - get: source
        trigger: true

      - task: settings
        params:
          ENV: ((environment))
        config:
          platform: linux
          inputs:
            - name: source
          outputs:
            - name: settings
          image_resource:
            type: docker-image
            source:
              repository: 005901988046.dkr.ecr.us-east-2.amazonaws.com/concourse-worker
              tag: latest
              aws_access_key_id: ((aws_access_key_id))
              aws_secret_access_key: ((aws_secret_access_key))
          run:
            dir: source
            path: make
            args:
              - settings

      - task: deploy-infrastructure
        params:
          ENV: ((environment))
          AWS_ACCESS_KEY_ID: ((aws_access_key_id))
          AWS_SECRET_ACCESS_KEY: ((aws_secret_access_key))
        config:
          platform: linux
          inputs:
            - name: source
            - name: settings
          outputs:
            - name: settings
          image_resource:
            type: docker-image
            source:
              repository: 005901988046.dkr.ecr.us-east-2.amazonaws.com/concourse-worker
              tag: latest
              aws_access_key_id: ((aws_access_key_id))
              aws_secret_access_key: ((aws_secret_access_key))
          run:
            dir: source
            path: make
            args:
              - deploy_infrastructure

      - task: deploy-lambda
        params:
          ENV: ((environment))
          AWS_ACCESS_KEY_ID: ((aws_access_key_id))
          AWS_SECRET_ACCESS_KEY: ((aws_secret_access_key))
        config:
          platform: linux
          inputs:
            - name: source
            - name: settings
          outputs:
            - name: settings
          image_resource:
            type: docker-image
            source:
              repository: 005901988046.dkr.ecr.us-east-2.amazonaws.com/concourse-worker
              tag: latest
              aws_access_key_id: ((aws_access_key_id))
              aws_secret_access_key: ((aws_secret_access_key))
          run:
            dir: source
            path: make
            args:
              - deploy_lambda
