resources:
  - name: source
    type: git
    source:
      uri: https://github.com/benbowden3/concourse-cicd-cmg.git

jobs:
  - name: kinesisToDynamo
    serial: true
    plan:
      - get: source
        trigger: true

      - task: settings
        params:
          ENV: ((environment))
          PIPELINE: 1
        config:
          platform: linux
          inputs:
            - name: source
          outputs:
            - name: settings
          image_resource:
            type: docker-image
            source:
              repository: 005901988046.dkr.ecr.us-east-1.amazonaws.com:443/concourse-worker
              tag: latest
              aws_access_key_id: ((aws_access_key_id))
              aws_secret_access_key: ((aws_secret_access_key))
          run:
            dir: source/kinesisToDynamo
            path: make
            args:
              - settings

      - task: infrastructure-deploy
        params:
          ENV: ((environment))
          PIPELINE: 1
          AWS_ACCESS_KEY_ID: ((aws_access_key_id))
          AWS_SECRET_ACCESS_KEY: ((aws_secret_access_key))
        config:
          platform: linux
          inputs:
            - name: source
            - name: settings
          outputs:
            - name: settings
          image_resource:
            type: docker-image
            source:
              repository: 005901988046.dkr.ecr.us-east-1.amazonaws.com:443/concourse-worker
              tag: latest
              aws_access_key_id: ((aws_access_key_id))
              aws_secret_access_key: ((aws_secret_access_key))
          run:
            dir: source/kinesisToDynamo/infrastructure
            path: make

      - task: lambda-test
        params:
          ENV: ((environment))
          PIPELINE: 1
        config:
          platform: linux
          inputs:
            - name: source
            - name: settings
          image_resource:
            type: docker-image
            source:
              repository: 005901988046.dkr.ecr.us-east-1.amazonaws.com:443/concourse-worker
              tag: latest
              aws_access_key_id: ((aws_access_key_id))
              aws_secret_access_key: ((aws_secret_access_key))
          run:
            dir: source/kinesisToDynamo/lambda
            path: make
            args:
              - test

      - task: lambda-build
        params:
          ENV: ((environment))
          PIPELINE: 1
        config:
          platform: linux
          inputs:
            - name: source
            - name: settings
          outputs:
            - name: source
            - name: build
          image_resource:
            type: docker-image
            source:
              repository: 005901988046.dkr.ecr.us-east-1.amazonaws.com:443/concourse-worker
              tag: latest
              aws_access_key_id: ((aws_access_key_id))
              aws_secret_access_key: ((aws_secret_access_key))
          run:
            dir: source/kinesisToDynamo/lambda
            path: make
            args:
              - build

      - task: lambda-deploy
        params:
          ENV: ((environment))
          PIPELINE: 1
          AWS_ACCESS_KEY_ID: ((aws_access_key_id))
          AWS_SECRET_ACCESS_KEY: ((aws_secret_access_key))
        config:
          platform: linux
          inputs:
            - name: settings
            - name: build
            - name: source
          image_resource:
            type: docker-image
            source:
              repository: 005901988046.dkr.ecr.us-east-1.amazonaws.com:443/concourse-worker
              tag: latest
              aws_access_key_id: ((aws_access_key_id))
              aws_secret_access_key: ((aws_secret_access_key))
          run:
            dir: source/kinesisToDynamo/lambda
            path: make
            args:
              - deploy

      - task: functional-tests
        params:
          ENV: ((environment))
          PIPELINE: 1
          AWS_ACCESS_KEY_ID: ((aws_access_key_id))
          AWS_SECRET_ACCESS_KEY: ((aws_secret_access_key))
        config:
          platform: linux
          inputs:
            - name: source
            - name: settings
          image_resource:
            type: docker-image
            source:
              repository: 005901988046.dkr.ecr.us-east-1.amazonaws.com:443/concourse-worker
              tag: latest
              aws_access_key_id: ((aws_access_key_id))
              aws_secret_access_key: ((aws_secret_access_key))
          run:
            dir: source/kinesisToDynamo/functional_tests
            path: make
            args:
              - test

  - name: s3mover
    serial: true
    plan:
      - get: source
        trigger: true
      - task: settings
        params:
          ENV: ((environment))
          PIPELINE: 1
        config:
          platform: linux
          inputs:
            - name: source
          outputs:
            - name: settings
          image_resource:
            type: docker-image
            source:
              repository: 005901988046.dkr.ecr.us-east-1.amazonaws.com:443/concourse-worker
              tag: latest
              aws_access_key_id: ((aws_access_key_id))
              aws_secret_access_key: ((aws_secret_access_key))
          run:
            dir: source/s3mover
            path: make
            args:            
              - settings

      # - task: functional-tests
      #       dir: source/s3mover
      #       path: make
      #         - settings


      # - task: lambda-test
      #   params:
      #     ENV: ((environment))
      #     PIPELINE: 1
      #   config:
      #     platform: linux
      #     inputs:
      #       - name: source
      #       - name: settings
          # image_resource:
          #   type: docker-image
          #   source:
          #     repository: 005901988046.dkr.ecr.us-east-1.amazonaws.com:443/concourse-worker
          #     tag: latest
          #     aws_access_key_id: ((aws_access_key_id))
          #     aws_secret_access_key: ((aws_secret_access_key))
          # run:
          #   dir: source/s3mover/lambda
          #   path: make
          #   args:
          #     - test

      - task: lambda-build
        params:
          ENV: ((environment))
          PIPELINE: 1
        config:
          platform: linux
          inputs:
            - name: source
            - name: settings
          outputs:
            - name: source
            - name: build
          image_resource:
            type: docker-image
            source:
              repository: 005901988046.dkr.ecr.us-east-1.amazonaws.com:443/concourse-worker
              tag: latest
              aws_access_key_id: ((aws_access_key_id))
              aws_secret_access_key: ((aws_secret_access_key))
          run:
            dir: source/s3mover
            path: make
            args:
              - build
      
      - task: infrastructure-deploy
        params:
          ENV: ((environment))
          AWS_ACCESS_KEY_ID: ((aws_access_key_id))
          AWS_SECRET_ACCESS_KEY: ((aws_secret_access_key))
        config:
          platform: linux
          inputs:
            - name: source
            - name: settings
          outputs:
            - name: settings
          image_resource:
            type: docker-image
            source:
              repository: 005901988046.dkr.ecr.us-east-1.amazonaws.com:443/concourse-worker
              tag: latest
              aws_access_key_id: ((aws_access_key_id))
              aws_secret_access_key: ((aws_secret_access_key))
          run:
            dir: source/s3mover/infrastructure
            path: make


 