service: ${file(../settings.json):environment}
app: concoursedemo-app

provider:
  name: aws
  region: ${file(../settings.json):region}
  runtime: nodejs12.x
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "kinesis:*"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "logs:*"
      Resource: "*"

# Include config with lambda
package:
  include:
    - infrastructure.json

functions:
  concoursedemo:
    handler: handler.handler

    events:
      - stream: ${file(../infrastructure/output.json):kinesis_stream.value}
